language: python
python: "2.7"
install:
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg -v 1.6.3
  - bin/buildout -c travis.cfg buildout:develop= buildout:auto-checkout= install download install 
  - bin/buildout -N -t 3 -c travis.cfg
script: 
  - bin/test -s ploneintranet.simplesharing
  - bin/flake8 src/ploneintranet
after_success:
  - bin/createcoverage run bin/test -s ploneintranet.simplesharing
  - pip install -q coveralls
  - coveralls
notifications:
  email: plone.intranet@netsight.co.uk
  irc: "chat.freenode.net#plone.intranet"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

